### ISSUE TITLE
cleanup ".well-known/acme-challenge/" dir after certificate creation

### ISSUE THREAD

**Issue by joos2k** [oetiker/AcmeFetch#16]
The client should delete all the challenge files after a successful certificate creation. Then it matches my use case perfectly. :-)

**Comment by qx-bug-importer** [comment]
since Protocol::ACME is creating the files, I guess it would be best if it deleted them too ... could you open your issue with https://github.com/sludin/Protocol-ACME/issues

**Comment by sludin** [comment]
I got this.  Thanks!

-stephen

**Comment by sludin** [comment]
I looked at this and have a plan but I do not have time execute it before I go on vacation tomorrow.  The idea is the add a ‘cleanup’ step to the challenge.  So the flow would look like:

```
 $acme->authz( $domain );
 $acme->handle_challenge( $challenges->{$domain} );
 $acme->check_challenge();
 $acme->cleanup_challenge();
```

or something like that.  I am back in front of a computer after the 16th.  If you have any suggestions or wishes just let me know.

-stephen

**Comment by oetiker** [comment]
couldn't check_challenge just do the cleanup ?

**Comment by sludin** [comment]
Yes - you are absolutely right.  I will add a cleanup method to the challenge object but it will get called automatically by check_challenge.  Good call.

-stephen

**Comment by joos2k** [comment]
I've made some changes (and only checked the LocalFile implementation, but the others should work too):
If it's too dirty, then forget it. ;-)

```
 lib/Protocol/ACME.pm                     | 16 ++++++++++++++++
 lib/Protocol/ACME/Challenge/LocalFile.pm | 25 +++++++++++++++++++++++++
 lib/Protocol/ACME/Challenge/Manual.pm    | 15 +++++++++++++++
 lib/Protocol/ACME/Challenge/SimpleSSH.pm | 10 ++++++++++
 4 files changed, 66 insertions(+)

diff --git a/lib/Protocol/ACME.pm b/lib/Protocol/ACME.pm
index ea3f21b..e27b412 100644
--- a/lib/Protocol/ACME.pm
+++ b/lib/Protocol/ACME.pm
@@ -750,6 +750,7 @@ sub handle_challenge
     $self->{fingerprint} = $fingerprint;
     $self->{token} = $token;
     $self->{links}->{challenge} = $challenge_url;
+    $self->{object} = $challenge;
   }
   else
   {
@@ -790,6 +791,21 @@ sub check_challenge
   }
 }

+sub cleanup_challenge
+{
+  my $self = shift;
+  
+  my $challenge = $self->{object};
+  my $token = $self->{token};
+  
+  my $ret = $challenge->cleanup( $token );
+  
+  if ( $ret != 0 )
+  {
+    _throw( status => 0, detail => $ret, type => "challenge_cleanup" );
+  }
+}
+
 sub sign
 {
   my $self = shift;
diff --git a/lib/Protocol/ACME/Challenge/LocalFile.pm b/lib/Protocol/ACME/Challenge/LocalFile.pm
index d70c2ae..7e083ea 100644
--- a/lib/Protocol/ACME/Challenge/LocalFile.pm
+++ b/lib/Protocol/ACME/Challenge/LocalFile.pm
@@ -139,6 +139,31 @@ sub handle
   return 0;
 }

+sub cleanup
+{
+  my $self          = shift;
+  my $challenge     = shift;
+  
+  # TODO: put the 'well known path' in a global variable somewhere
+  if (not -d $self->{www_root}){
+      carp "$self->{www_root} does not exist\n";
+  }
+  # if we are root this will make us into the correct user for the site
+  my ($uid,$gid) = (stat $self->{www_root})[4,5];
+  local $> = $uid;local $) = $gid;
+  my $dir = "$self->{www_root}/.well-known/acme-challenge";
+  my $filename = "$dir/$challenge";
+  system "rm",$filename;
+  
+  if ( $? != 0 )
+  {
+    carp "Could not remove $filename";
+    return 1;
+  }
+
+  return 0;
+}
+
 =head1 AUTHOR

 Stephen Ludin, C<< <sludin at ludin.org> >>
diff --git a/lib/Protocol/ACME/Challenge/Manual.pm b/lib/Protocol/ACME/Challenge/Manual.pm
index 489f477..f9b6f44 100644
--- a/lib/Protocol/ACME/Challenge/Manual.pm
+++ b/lib/Protocol/ACME/Challenge/Manual.pm
@@ -95,6 +95,21 @@ sub handle
   return 0;
 }

+sub cleanup
+{
+  my $self          = shift;
+  my $challenge     = shift;
+
+  my $filename = $challenge;
+
+  print "Challenge filename: $challenge\n";
+  print "\n";
+  print "Delete the file with the above filename under <WWW>/.well-known/acme-challenge\n";
+  print "where <WWW> is your web server's document root.\n";
+
+  return 0;
+}
+
 =head1 AUTHOR

 Stephen Ludin, C<< <sludin at ludin.org> >>
diff --git a/lib/Protocol/ACME/Challenge/SimpleSSH.pm b/lib/Protocol/ACME/Challenge/SimpleSSH.pm
index 11b6a57..7718293 100644
--- a/lib/Protocol/ACME/Challenge/SimpleSSH.pm
+++ b/lib/Protocol/ACME/Challenge/SimpleSSH.pm
@@ -120,6 +120,16 @@ sub handle
   return $? == 0 ? 0 : 1;
 }

+sub cleanup
+{
+  my $self          = shift;
+  my $challenge     = shift;
+  my $dir = "$self->{www_root}/.well-known/acme-challenge";
+  my @cmd = ('ssh', '-q',  $self->{ssh_host}, "rm '$dir/$challenge'");
+  system @cmd;
+  return $? == 0 ? 0 : 1;
+}
+
 =head1 AUTHOR

 Stephen Ludin, C<< <sludin at ludin.org> >>
```

**Comment by sludin** [comment]
It could roll either way - you are right that it does not store any state between calls today, but that would be simple to fix. I am good with either direction. 

-stephen

**Comment by sludin** [comment]
Back from vacation with something more than a phone in front of me.

Because I made the ACME object stateless in terms of challenges an auto cleanup is not practical.  It feels awkward, but because of choices made before the only straightforward choice is to add a call like:
$acme->cleanup_challenge( $challenge );

Leaving the flow to look like:

```
$acme->authz( $domain );
$acme->handle_challenge( $challenge );
$acme->check_challenge();
$acme->cleanup_challenge( $challenge );
```

I have no problem with that beyond the fact that something bugs me about passing the challenge in twice, but I can get over that.  It leaves open the possibility of a debug mode where the challenge file is not removed.

The ACME method would simply be:

sub cleanup_challenge
{
  my $self            = shift;
  my $challenge = shift;
  return $challenge->cleanup();
}

Which means an equivalent flow would be:

```
$acme->authz( $domain );
$acme->handle_challenge( $challenge );
$acme->check_challenge();
$challenge->cleanup();
```

All feedback welcome.

-stephen

**Comment by oetiker** [comment]
I guess I would use the `$challenge->cleanup();` variant then.

**Comment by sludin** [comment]
Changes are committed.  I’ll wait a bit for commends before I push a new CPAN version.

-stephen

From:  Stephen Ludin sludin@ludin.org
Date:  Monday, April 18, 2016 at 9:37 AM
To:  oetiker/AcmeFetch reply@reply.github.com, oetiker/AcmeFetch AcmeFetch@noreply.github.com, Felipe Gasper felipe@felipegasper.com
Subject:  Re: [oetiker/AcmeFetch] cleanup ".well-known/acme-challenge/" dir after certificate creation (#16)

Back from vacation with something more than a phone in front of me.

Because I made the ACME object stateless in terms of challenges an auto cleanup is not practical.  It feels awkward, but because of choices made before the only straightforward choice is to add a call like:
$acme->cleanup_challenge( $challenge );

Leaving the flow to look like:

```
$acme->authz( $domain );
$acme->handle_challenge( $challenge );
$acme->check_challenge();
$acme->cleanup_challenge( $challenge );
```

I have no problem with that beyond the fact that something bugs me about passing the challenge in twice, but I can get over that.  It leaves open the possibility of a debug mode where the challenge file is not removed.

The ACME method would simply be:

sub cleanup_challenge
{
  my $self            = shift;
  my $challenge = shift;
  return $challenge->cleanup();
}

Which means an equivalent flow would be:

```
$acme->authz( $domain );
$acme->handle_challenge( $challenge );
$acme->check_challenge();
$challenge->cleanup();
```

All feedback welcome.

-stephen

**Comment by FGasper** [comment]
What about this:

```
$acme->authz( $domain );
{
    my $handler = $acme->handle_challenge( $challenge );
    $acme->check_challenge();
}
```

**Comment by FGasper** [comment]
… then the DESTROY on the $handler would be what cleans up the file.

**Comment by oetiker** [comment]
the new version should work better
